### ISSUE TITLE
nix-build -A broken in 0.3.6

### ISSUE THREAD

**Issue by ledettwy** [spwhitt/nix-zsh-completions#8] opened 2017-12-11 09:15 UTC
Zsh completions for nix-build -A appears to have gotten broken in 0.3.6. When I checkout 60d3a112512da92ba14bd0df215623bf9bccd8f0 in nixpkgs it doesn't work, but when I checkout b4d2c46e56c5307470bbbf63abab2112d872a915 in nixpkgs it works.

**Comment by hedning** [comment] 2017-12-11 10:04
Hmm, I'm unable to reproduce it here, any errors?

If there's not any obvious errors printed out, could you do `nix-build -A <C-x ?>` (that is `CTRL-x ?` instead of `tab`). It will give you something like this:
```
$ nix-build -A 
Trace output left in /tmp/zsh23272nix-build3 (up-history to view)
```
And post the file to a gist service (it's pretty large).

**Comment by ledettwy** [comment] 2017-12-14 20:04
Sure, I'll try to do that soon.

**Comment by ledettwy** [comment] 2017-12-20 21:37
`nix-build -A packages`
Expected result: `nix-build -A packages.`
Actual result: `nix-build -A packages`

https://gist.github.com/ledettwy/7a0842b3941ec881c7f53a8b6393f9e4

Instead it just beeps at me with no indication as to what's wrong ):.  Usually when this happens, I can try to evaluate it and Nix will show me my syntax error or something, but this Nix code evaluates and builds just fine if I manually type out a path, but the tab-complete just beeps at me.

nix-info: system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.11.16, channels(root): "nixos-17.09.2430.ed3b1bc8448, unstable-18.03pre123130.1bc288591ea", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

**Comment by hedning** [comment] 2017-12-20 22:23
Ah, sorry, managed to leave a `2> /dev/null` in the code that calls the function actually doing the last completion, so the trace stopped exactly where it could be useful :(. (pushing a fix for that so if it's not too much hassle to run the `C-x ?` thing against master that would be great).

If I understand correctly it's a specific `default.nix` it fails on. Is the repo public? That could be helpful to look at.

Another possibility: does the `default.nix` (or other files referenced) contain any URLs that would need to be downloaded for attribute name evaluation to happen (eg. `with some-url;`)? Not sure how well I handle those cases, as nix-instantiate will try to download things that's needed for the completion to happen (if things are cached). Though if the issue persist after a successful evaluation that shouldn't really the problem.

**Comment by ledettwy** [comment] 2017-12-20 22:26
I'll try to setup my nixpkgs to pull from master of this repo and I'll retest. Unfortunately the Nix tree I'm running this on has some sensitive data in it and is somewhat large, which will make figuring this out a bit difficult ): I'll try master later today and post a new C-x ?

**Comment by hedning** [comment] 2017-12-20 22:32
No worries, I'll see if I can figure it out from a full completion trace :)

Something like this in `~/.zshrc` should work, to load from a specific path:
```zsh
fpath=(~/path/to/nix-zsh-completions $fpath)
```

**Comment by olejorgenb** [comment] 2017-12-20 22:34
You might need to run `compinit` after modifying `fpath` too.

**Comment by olejorgenb** [comment] 2017-12-20 22:46
You can also just check that the following evaluates to a list of attribute names

```
nix-instantiate --eval - <<EOF
        let
        top_gen = import /root/lisanna-nix-channel/default.nix {};
        # --file arguments can be a lambda producing a record too
        top = if builtins.typeOf top_gen == "lambda" then top_gen {} else top_gen ;
        in
            builtins.attrNames top
EOF
```

**Comment by ledettwy** [comment] 2017-12-31 16:52
`top_gen = import /root/lisanna-nix-channel/default.nix {};` fails because my default.nix is a set, not a function. If I change it to `top_gen = import /root/lisanna-nix-channel/default.nix;` then it prints all the expected attributes.

<pre>
[1] root@citadel> fpath=(/root/nix-zsh-completions /nix/store/xx30fna7ghndqkgz9vxqa8pn8zmb1cw9-zsh-5.4.2/share/zsh/5.4.2/functions)                                                                                                                                                                                                                                     ~/lisanna-nix-channel
root@citadel> echo $fpath                                                                                                                                                                                                                                                                                                                                               ~/lisanna-nix-channel
/root/nix-zsh-completions /nix/store/xx30fna7ghndqkgz9vxqa8pn8zmb1cw9-zsh-5.4.2/share/zsh/5.4.2/functions
root@citadel> compinit                                                                                                                                                                                                                                                                                                                                                  ~/lisanna-nix-channel
root@citadel> nix-build -A                                                                                                                                                                                                                                                                                                                                              ~/lisanna-nix-channel
[130] root@citadel>
</pre>

https://gist.github.com/ledettwy/881999d4ff20037ca5f2d339835916b8

**Comment by hedning** [comment] 2017-12-31 17:43
Ah, that makes sense. When I added argument completion I silently assumed that the top level was a function, which obviously is wrong. Will make a fix.

Thanks for getting to the bottom of it :)

**Comment by ledettwy** [comment] 2018-01-01 03:16
Awesome, that fixed it!

**Comment by hedning** [comment] 2018-01-10 09:18
The fix is in nixpkgs master now, and should get backported soon, so closing this.

Thanks again for reporting and discovering this rather serious regression.

**Closed by hedning** 2018-01-10 09:18 UTC
